# Generated by Django 4.2.19 on 2025-03-08 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiotextfile",
            old_name="audio",
            new_name="is_audio",
        ),
        migrations.AlterField(
            model_name="audiotextfile",
            name="saver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Загрузивший пользователь",
            ),
        ),
    ]
