# Generated by Django 4.2.19 on 2025-03-08 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0002_rename_audio_audiotextfile_is_audio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="myusers.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="text_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call",
                to="myusers.audiotextfile",
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="text_pure",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call",
                to="myusers.textpure",
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
