# Generated by Django 4.2.19 on 2025-03-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0003_alter_call_opponent_alter_call_text_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textpure",
            name="id_doc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_content",
                to="myusers.audiotextfile",
                verbose_name="Файл",
            ),
        ),
    ]
