# Generated by Django 4.2.19 on 2025-03-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0004_alter_textpure_id_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purpose",
            name="price_month",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена за месяц",
            ),
        ),
        migrations.AlterField(
            model_name="purpose",
            name="price_one_file",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена за один файл",
            ),
        ),
    ]
