# Generated by Django 4.2.19 on 2025-03-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0005_alter_purpose_price_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="text_pure",
        ),
    ]
