# Generated by Django 4.2.19 on 2025-03-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0006_remove_call_text_pure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiotextfile",
            name="saver",
        ),
    ]
