# Generated by Django 4.2.19 on 2025-03-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0007_remove_audiotextfile_saver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opponent",
            name="position",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Должность"
            ),
        ),
    ]
