# Generated by Django 4.2.20 on 2025-05-13 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0008_alter_opponent_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Должность представителя",
                    ),
                ),
                (
                    "responsibility",
                    models.TextField(
                        blank=True, null=True, verbose_name="Зона ответственности"
                    ),
                ),
                (
                    "name_input",
                    models.CharField(
                        max_length=255, verbose_name="Исходное название файла"
                    ),
                ),
                (
                    "name_save",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Сохраненное название файла",
                    ),
                ),
                (
                    "data_save",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "is_audio",
                    models.BooleanField(default=False, verbose_name="Аудиофайл"),
                ),
                (
                    "audio_length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Длина аудиозаписи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание запроса"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Тип данных"
                    ),
                ),
                (
                    "data_type_short",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Краткий тип данных",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество документов в месяц",
                    ),
                ),
                (
                    "price_month",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена за месяц",
                    ),
                ),
                (
                    "price_one_file",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена за файл",
                    ),
                ),
                (
                    "lead",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Успех"),
                            ("fail", "Неудача"),
                            ("hesitant", "Неопределённый"),
                            (None, "Нет данных"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Успешность касания",
                    ),
                ),
                (
                    "fail_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Причина отказа"
                    ),
                ),
                (
                    "area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование области",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Касание",
                "verbose_name_plural": "Касания",
                "unique_together": {("id", "name_save")},
            },
        ),
    ]
