# Generated by Django 4.2.20 on 2025-05-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0010_callitem_area_callitem_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="callitem",
            name="next_place",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Время и место следующей встречи",
            ),
        ),
    ]
