# Generated by Django 4.2.20 on 2025-05-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0011_callitem_next_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="callitem",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Телефон представителя",
            ),
        ),
    ]
