# Generated by Django 4.2.20 on 2025-05-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myusers", "0013_callitem_name_audio_to_txt"),
    ]

    operations = [
        migrations.AddField(
            model_name="callitem",
            name="do_clean",
            field=models.BooleanField(
                default=False, verbose_name="Необходимость в предобработке"
            ),
        ),
        migrations.AddField(
            model_name="callitem",
            name="name_file_cleaned",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Название очищенного аудио файла",
            ),
        ),
    ]
